### ISSUE TITLE
Refactor scheduler / searcher interface

### ISSUE THREAD

**Issue by aaronkl** [syne-tune/syne-tune#879]
The current interfaces for schedulers and searchers are flexible and highly configurable, but they can be difficult to understand and maintain. The FIFOScheduler in particular is complex and not easily adaptable. To encourage wider adoption of the library—especially among HPO developers—and to reduce maintenance overhead, I suggest simplifying the current scheduler and searcher interfaces by:

- Removing boilerplate code
- Minimizing the base class and removing specific class logic
- Creating a cleaner separation between scheduler and searcher
- Avoiding mutation of kwargs objects
- Explicitly handling both single-objective and multi-objective searchers

# Tasks

- [x] add new interface for single-fidelity and multi-fidelity scheduling #877 
- [x] add new interface for single and multi-objective searcher #878 
- [x] deprecate current FIFO and Hyperband scheduler
- [x] migrate existing single-fidelity scheduler / searchers to new interface.
    - [x] RandomSearcher  
    - [x] BORE
    - [x] REA
    - [x] KDE
    - [x] CQR
    - [x] GP-BO
    - [x] SMAC

- [x] migrate existing multi-fidelity scheduler / searchers to new interface.
    - [x] ASHA
    - [x] Model-based ASHA
    - [x] Median Stopping Rule
    - [x] PBT
  
- [x] migrate multi-objective methods
   - [X] EHVI
   - [x] Linear scalarization
   - [x] MO-ASHA
   
- [x] migrate transfer-learning methods
   - [x] bounding box 
   - [x] zero-shot
   - [x] quantile
- [x] update doc-strings
- [x] update baselines.py
